# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

#      - name: Execute Gradle build
#        run: ./gradlew build 
        
      - name: Gradle Build with Sonarqube
        # You may pin to the exact commit or the version.
        # uses: trideepnag1911/gradle-build-with-sonarqube@c35e2952f05e7e45fd81a774a9abab46f132a306
        uses: trideepnag1911/gradle-build-with-sonarqube@v1.0
        env:
         SONAR_TOKEN: tfo2wmdqjoqekbkwduhwmasij6e5pyrs3j3zi6urof6nqxwq6jsq
          
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
         SONAR_TOKEN: tfo2wmdqjoqekbkwduhwmasij6e5pyrs3j3zi6urof6nqxwq6jsq
         SONAR_HOST_URL: https://sonarcloud.io



      - name: script sonar
        run: |
          tree

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 300
        env:
         SONAR_TOKEN: 4114ccd2d25c49e59397eacc3c9bd4b0f32572b7        

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: $GITHUB_ACTION_REPOSITORY
